on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    
    - uses: gradle/actions/setup-gradle@v4

    - name: Run Gradle build
      run: gradle build

    - name: Upload jar
      uses: actions/upload-artifact@v3
      with:
        name: deobfuscator
        path: |
          build/libs/*
